[build]
  base    = "admin"
  command = "node -v && npm -v && npm ci || (rm -rf node_modules package-lock.json && npm install) && npm run build -- --debug"
  publish = "admin/dist"

[build.environment]
  NODE_VERSION      = "20"
  NPM_CONFIG_LOGLEVEL = "verbose"
  CI = "true"
