[build]
  base    = "admin"
  command = "npm ci && npm run build"
  publish = "admin/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS    = "--no-fund --no-audit"

# Single Page App routing
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Referrer-Policy    = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options    = "DENY"
