[build]
  base    = "admin"
  # Install without optional native binaries to avoid npm optional-deps bug on CI
  command = "npm ci --no-optional && npm run build"
  # When base = "admin", publish should be "dist" (NOT "admin/dist")
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS    = "--no-optional"
