[build]
  base    = "admin"
  command = "node -v && npm -v && npm install --omit=optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  ROLLUP_SKIP_NODE_BINARY = "true"

# Optional SPA fallback (keeps it here so Netlify reads a single config file)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
